[package]
name = "csv"
version = "0.2.0"
authors = ["steve"]

[profile.release]
lto=true
opt-level = 3
#panic = 'abort'
debug = false
debug-assertions = false
target-cpus='native'

[[bin]]
name = "csv"
path = "src/csv.rs"

[dependencies]
csv = "1"
regex = "1"
prettytable-rs = "^0.6"
chan = "0.1.21"
fnv = "1.0.6"

chashmap = "2.2.0"

