[package]
name = "csv"
version = "0.4.0"
authors = ["steve"]

[profile.dev]
panic = 'abort'

[profile.release]
lto=true
codegen-units = 1
opt-level = 3
panic = 'abort'
debug = false
debug-assertions = false
#target-cpus='native'

[[bin]]
name = "csv"
path = "src/csv.rs"

[[test]]
name = "general_tests"
path = "src/test.rs"

[dependencies]
structopt = {version = "0.2.18", feature=["color","termsize","wrap_help"]}
csv = "~1"
regex = "~1"
prettytable-rs = "~0.6"
chan = "~0.1.21"
lazy_static = "1.3.0"
crossbeam-channel = "~0.3.6"
crossbeam = "~0.7"

num_cpus = "1.0"

assert_cmd = "0.10"
predicates = "1"


